version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - dastanko
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.1
    - 3.4.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: django-money
    versions:
    - "1.3"
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: django-registration-redux
    versions:
    - "2.8"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - dastanko
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: lodash
    versions:
    - 4.17.20
