# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0037_add_fields_to_iteration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='start_datetime',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
