# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import orchestra.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchestra', '0044_auto_20160426_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'slack'), (1, 'email')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=(orchestra.utils.models.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='communicationpreference',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestra.CommunicationType'),
        ),
        migrations.AddField(
            model_name='communicationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
