# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 03:02
from __future__ import unicode_literals

from django.db import migrations

def create_task_change_communcation_type(apps, schema_editor):
    CommunicationType = apps.get_model(
        'orchestra', 'CommunicationType')

    CommunicationType.objects.create(
        slug='task_status_change', description='Task status has changed')


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0045_auto_20160426_0302'),
    ]

    operations = [
        migrations.RunPython(create_task_change_communcation_type)  # manually-reviewed
    ]
