# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 06:44
from __future__ import unicode_literals

from enum import Enum

from django.db import migrations

# Copy pasted from models since migrations does not have access
class CommunicationMethods(object):
    SLACK = 'slack'
    EMAIL = 'email'


COMMUNICATION_METHODS = (
    (CommunicationMethods.SLACK, 'Slack'),
    (CommunicationMethods.EMAIL, 'Email'),
)

class CommunicationType(Enum):
    TASK_STATUS_CHANGE = 0
    NEW_TASK_AVAILABLE = 1

def add_communication_type(apps, schema_editor):
    Worker = apps.get_model('orchestra', 'Worker')
    CommunicationPreference = apps.get_model('orchestra',
                                             'CommunicationPreference')
    communication_type = (
        CommunicationType.NEW_TASK_AVAILABLE.value)
    for worker in Worker.objects.all():
        communication_preference, created = (
            CommunicationPreference.objects.get_or_create(
                worker=worker,
                communication_type=communication_type))

        # By default set both Slack and Email notifications to True
        if created:
            communication_preference.methods.slack = True
            communication_preference.methods.email = True
        communication_preference.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0055_auto_20160429_0823'),
    ]

    operations = [
        migrations.RunPython(add_communication_type),  # manually-reviewed
    ]
