# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orchestra.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0069_update_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='orchestra.Task')),
            ],
            bases=(orchestra.utils.models.DeleteMixin, models.Model),
        ),
    ]
