# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-15 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0070_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orchestra.Worker'),
        ),
    ]
