# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0075_auto_20180111_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
