# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orchestra.models.core.mixins
import orchestra.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0077_auto_20180629_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approval_reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa', to='orchestra.Todo', unique=True)),
            ],
            bases=(orchestra.models.core.mixins.TodoQAMixin, orchestra.utils.models.DeleteMixin, models.Model),
        ),
    ]
