# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0078_todoqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='todolist_templates_to_apply',
            field=models.ManyToManyField(blank=True, to='orchestra.TodoListTemplate'),
        ),
    ]
