# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-01 18:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0078_todoqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='todolist_templates_to_apply',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
