# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0078_todoqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoqa',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoqa',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='todoqa',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa', to='orchestra.Todo'),
        ),
    ]
