# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models

PROJECT_STATUS_COMPLETED = 4
PROJECT_STATUS_ABORTED = 2

TASK_STATUS_COMPLETED = 5

def mark_completed_projects(apps, schema_editor):
    Project = apps.get_model('orchestra', 'Project')
    Task = apps.get_model('orchestra', 'Task')
    for project in Project.objects.all():
        workflow_version = project.workflow_version
        all_steps = workflow_version.steps.all()
        completed_tasks = Task.objects.filter(
            status=TASK_STATUS_COMPLETED,
            project=project)
        completed_step_slugs = set(
            completed_tasks.values_list('step__slug', flat=True))

        if (len(all_steps) == len(completed_step_slugs) and
                project.status != PROJECT_STATUS_ABORTED):
            project.status = PROJECT_STATUS_COMPLETED
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0079_auto_20180806_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (2, 'Aborted'), (3, 'Paused'), (4, 'Completed')], default=0),
        ),
        migrations.RunPython(mark_completed_projects)  # manually-reviewed
    ]
