# Generated by Django 2.2.13 on 2020-09-04 14:49

from django.db import migrations
from django.db.models import F
from django.db.models import OuterRef
from django.db.models import Subquery


def fill_project_and_step_fields(apps, schema_editor):
    Step = apps.get_model('orchestra', 'Step')
    Project = apps.get_model('orchestra', 'Project')
    Todo = apps.get_model('orchestra', 'Todo')
    o = OuterRef('id')
    step_outerref_filter_qs = Step.objects.filter(tasks__todos__id=o)
    project_outterref_filter_qs = Project.objects.filter(tasks__todos__id=o)
    subq_step = step_outerref_filter_qs.values('id')[:1]
    subq_proj = project_outterref_filter_qs.values('id')[:1]
    Todo.objects.update(project=Subquery(subq_proj), step=Subquery(subq_step))

class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0086_add_fields_to_todo'),
    ]

    operations = [
        migrations.RunPython(fill_project_and_step_fields,  # manually-reviewed
                             reverse_code=migrations.RunPython.noop),  # manually-reviewed
    ]
