# Generated by Django 2.2.13 on 2020-09-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0088_change_related_name_todos_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='completion_ends_project',
            field=models.BooleanField(default=False),
        ),
    ]
