# Generated by Django 2.2.13 on 2020-10-23 09:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0090_step_completion_ends_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
