# Generated by Django 2.2.13 on 2020-11-19 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orchestra.models.core.mixins
import orchestra.models.core.models
import orchestra.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0090_step_completion_ends_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('week', models.DateField(default=orchestra.models.core.models.WorkerPreferences.first_day_of_this_week)),
                ('hours_available_mon', models.FloatField(default=0)),
                ('hours_available_tues', models.FloatField(default=0)),
                ('hours_available_wed', models.FloatField(default=0)),
                ('hours_available_thurs', models.FloatField(default=0)),
                ('hours_available_fri', models.FloatField(default=0)),
                ('hours_available_sat', models.FloatField(default=0)),
                ('hours_available_sun', models.FloatField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestra.Worker')),
            ],
            options={
                'abstract': False,
            },
            bases=(orchestra.models.core.mixins.WorkerPreferencesMixin, orchestra.utils.models.DeleteMixin, models.Model),
        ),
    ]
