# Generated by Django 2.2.13 on 2020-11-19 20:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0092_update_staffing_enums'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='assignable_hours_function',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
