# Generated by Django 2.2.13 on 2021-07-29 10:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0096_todo_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolisttemplate',
            name='is_todo_required_function',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
