name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.15
          export PATH="$HOME/.yarn/bin:$PATH"
          yarn global add gulp

      - name: Install js and python dependencies
        run: |
          yarn
          # circle has a really old version of pip by default which seems to break
          # builds sometimes.
          pip install --upgrade pip==20.2.4
          pip install -r requirements.txt
          pip install coveralls

      - name: Run tests
        run: |
          make lint
          make coverage
          make coveralls
          # Circle uses XUnit reports
          mkdir -p $CIRCLE_TEST_REPORTS/python/
          find . -wholename *nosetests.xml -exec mv {} $CIRCLE_TEST_REPORTS/python/ \;
